import { User, Appointment, MedicalRecord, Prescription, LabResult, NotificationItem, SystemLog, Department } from './types';

export const INITIAL_USERS: User[] = [
  // Patients
  {
    id: 'user-pat-1',
    name: 'Emmanuel O. Kalu',
    email: 'emmanuel.kalu@example.com',
    role: 'patient',
    patientId: 'PID-2024-0418',
    phone: '+234 803 241 9870',
    dateOfBirth: '1992-05-14',
    gender: 'Male',
    bloodGroup: 'O+',
    genotype: 'AA',
    allergies: ['Penicillin', 'Sulfa drugs'],
    emergencyContact: {
      name: 'Blessing Kalu',
      relationship: 'Spouse',
      phone: '+234 802 119 4432',
    },
    address: 'Plot 14, University Crescent, Academic District',
    registeredDate: '2023-11-10',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-pat-2',
    name: 'Amina Bello',
    email: 'amina.bello@example.com',
    role: 'patient',
    patientId: 'PID-2024-0522',
    phone: '+234 814 670 3321',
    dateOfBirth: '1998-09-22',
    gender: 'Female',
    bloodGroup: 'B+',
    genotype: 'AS',
    allergies: ['Dust', 'Shellfish'],
    emergencyContact: {
      name: 'Ibrahim Bello',
      relationship: 'Father',
      phone: '+234 809 334 1290',
    },
    address: 'Block C, Faculty Staff Quarters',
    registeredDate: '2024-01-15',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-pat-3',
    name: 'Chinedu Eze',
    email: 'chinedu.eze@example.com',
    role: 'patient',
    patientId: 'PID-2024-0604',
    phone: '+234 701 988 5642',
    dateOfBirth: '1985-12-03',
    gender: 'Male',
    bloodGroup: 'A+',
    genotype: 'AA',
    allergies: ['None declared'],
    emergencyContact: {
      name: 'Ngozi Eze',
      relationship: 'Sister',
      phone: '+234 805 771 9022',
    },
    address: '22 Community Road, South Campus',
    registeredDate: '2024-02-28',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },

  // Doctors
  {
    id: 'user-doc-1',
    name: 'Dr. Sarah Mitchell',
    email: 's.mitchell@ehealth.edu',
    role: 'doctor',
    specialization: 'General Medicine & Family Health',
    department: 'Internal Medicine',
    licenseNumber: 'MD-MED-84920',
    yearsOfExperience: 9,
    availability: 'Mon - Thu (08:00 AM - 02:00 PM)',
    phone: '+234 803 700 8123',
    bio: 'Consultant Physician specializing in internal medicine, chronic disease management, and preventive healthcare programs.',
    qualifications: ['MBBS (UniLag)', 'FWACP (Internal Med)', 'MPH (Health Informatics)'],
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-doc-2',
    name: 'Dr. Daniel Adeyemi',
    email: 'd.adeyemi@ehealth.edu',
    role: 'doctor',
    specialization: 'Cardiology & Cardiovascular Care',
    department: 'Cardiology',
    licenseNumber: 'MD-CARD-39104',
    yearsOfExperience: 14,
    availability: 'Tue, Wed, Fri (09:00 AM - 03:30 PM)',
    phone: '+234 802 889 0012',
    bio: 'Senior Cardiologist with extensive clinical expertise in hypertension management, echocardiography, and coronary artery assessment.',
    qualifications: ['MBBS (Ibadan)', 'FMCP (Cardiology)', 'Fellow of European Society of Cardiology'],
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-doc-3',
    name: 'Dr. Fatima Umar',
    email: 'f.umar@ehealth.edu',
    role: 'doctor',
    specialization: 'Pediatrics & Child Health',
    department: 'Pediatrics',
    licenseNumber: 'MD-PED-55209',
    yearsOfExperience: 7,
    availability: 'Mon, Wed, Fri (08:30 AM - 01:30 PM)',
    phone: '+234 806 441 9920',
    bio: 'Dedicated Pediatrician focused on infant nutrition, immunizations, developmental milestones, and pediatric infectious disease.',
    qualifications: ['MBBS (ABU Zaria)', 'FWACP (Pediatrics)'],
    avatar: 'https://images.unsplash.com/photo-1594824813689-d9d9f05f7fa9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-doc-4',
    name: 'Dr. Kingsley Nwosu',
    email: 'k.nwosu@ehealth.edu',
    role: 'doctor',
    specialization: 'Orthopedics & Trauma Surgery',
    department: 'Surgery & Orthopedics',
    licenseNumber: 'MD-ORTH-11843',
    yearsOfExperience: 11,
    availability: 'Mon, Thu (10:00 AM - 04:00 PM)',
    phone: '+234 818 552 3310',
    bio: 'Consultant Orthopedic Surgeon managing musculoskeletal trauma, joint disorders, and sports-related injuries.',
    qualifications: ['MBBS (UNN)', 'FWACS (Orthopedics)'],
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-doc-5',
    name: 'Dr. Helen Davies',
    email: 'h.davies@ehealth.edu',
    role: 'doctor',
    specialization: 'Obstetrics & Gynecology',
    department: 'Women\'s Health',
    licenseNumber: 'MD-OBGYN-77319',
    yearsOfExperience: 12,
    availability: 'Tue, Thu, Sat (09:00 AM - 02:00 PM)',
    phone: '+234 809 663 1184',
    bio: 'Specialist in maternal-fetal medicine, prenatal care routines, reproductive endocrinology, and minimally invasive gynecological care.',
    qualifications: ['MBBS (Benin)', 'FMCOG', 'Diploma in Minimal Access Surgery'],
    avatar: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=150&auto=format&fit=crop&q=80',
  },

  // Admin
  {
    id: 'user-admin-1',
    name: 'Prof. J. C. Okafor (System Admin)',
    email: 'admin@ehealth.edu',
    role: 'admin',
    phone: '+234 803 000 1122',
    bio: 'Hospital Informatics Administrator and Academic System Supervisor.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-1',
    name: 'Internal Medicine',
    headOfDepartment: 'Dr. Sarah Mitchell',
    description: 'Diagnosis and management of non-surgical acute and chronic adult ailments.',
    doctorCount: 6,
    contactExtension: 'Ext. 401',
  },
  {
    id: 'dept-2',
    name: 'Cardiology',
    headOfDepartment: 'Dr. Daniel Adeyemi',
    description: 'Comprehensive cardiovascular evaluations, ECG, Holter monitoring, and hypertension clinic.',
    doctorCount: 4,
    contactExtension: 'Ext. 405',
  },
  {
    id: 'dept-3',
    name: 'Pediatrics',
    headOfDepartment: 'Dr. Fatima Umar',
    description: 'Clinical care for neonates, children, and adolescents, including immunization tracking.',
    doctorCount: 5,
    contactExtension: 'Ext. 408',
  },
  {
    id: 'dept-4',
    name: 'Surgery & Orthopedics',
    headOfDepartment: 'Dr. Kingsley Nwosu',
    description: 'Trauma management, orthopedic consultations, joint assessments, and minor surgical procedures.',
    doctorCount: 4,
    contactExtension: 'Ext. 412',
  },
  {
    id: 'dept-5',
    name: 'Women\'s Health & OB-GYN',
    headOfDepartment: 'Dr. Helen Davies',
    description: 'Antenatal care, gynecological evaluations, maternal health, and postnatal check-ups.',
    doctorCount: 4,
    contactExtension: 'Ext. 416',
  },
  {
    id: 'dept-6',
    name: 'Pathology & Diagnostic Laboratory',
    headOfDepartment: 'Dr. A. B. Cole',
    description: 'Hematology, biochemistry, microbiology cultures, urinalysis, and histological services.',
    doctorCount: 3,
    contactExtension: 'Ext. 420',
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-101',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    patientPhone: '+234 803 241 9870',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    department: 'Internal Medicine',
    specialization: 'General Medicine & Family Health',
    date: '2026-08-25',
    time: '10:30',
    reason: 'Routine quarterly check-up and follow-up on mild hypertension management.',
    symptoms: 'Occasional morning dizziness, mild fatigue.',
    status: 'Upcoming',
    roomNumber: 'Consultation Room 3B',
    createdAt: '2026-08-15',
  },
  {
    id: 'apt-102',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    patientPhone: '+234 803 241 9870',
    doctorId: 'user-doc-2',
    doctorName: 'Dr. Daniel Adeyemi',
    department: 'Cardiology',
    specialization: 'Cardiology & Cardiovascular Care',
    date: '2026-09-02',
    time: '11:15',
    reason: 'Follow-up ECG review and lipid panel evaluation.',
    symptoms: 'Mild chest tightness after strenuous walking.',
    status: 'Upcoming',
    roomNumber: 'Cardiology Clinic Wing 2',
    createdAt: '2026-08-17',
  },
  {
    id: 'apt-103',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    patientPhone: '+234 803 241 9870',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    department: 'Internal Medicine',
    specialization: 'General Medicine & Family Health',
    date: '2026-07-10',
    time: '09:00',
    reason: 'Treatment of persistent upper respiratory tract infection and fever.',
    symptoms: 'Dry cough, sore throat, fever of 38.2°C.',
    status: 'Completed',
    notes: 'Prescribed antibiotics and antipyretics. Symptoms resolved on 5-day review.',
    roomNumber: 'Consultation Room 3B',
    createdAt: '2026-07-05',
  },
  {
    id: 'apt-104',
    patientId: 'PID-2024-0522',
    patientName: 'Amina Bello',
    patientPhone: '+234 814 670 3321',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    department: 'Internal Medicine',
    specialization: 'General Medicine & Family Health',
    date: '2026-08-20',
    time: '09:45',
    reason: 'General medical clearance and annual wellness examination.',
    symptoms: 'None, routine academic staff medical check.',
    status: 'Upcoming',
    roomNumber: 'Consultation Room 3B',
    createdAt: '2026-08-16',
  },
  {
    id: 'apt-105',
    patientId: 'PID-2024-0604',
    patientName: 'Chinedu Eze',
    patientPhone: '+234 701 988 5642',
    doctorId: 'user-doc-4',
    doctorName: 'Dr. Kingsley Nwosu',
    department: 'Surgery & Orthopedics',
    specialization: 'Orthopedics & Trauma Surgery',
    date: '2026-08-22',
    time: '14:00',
    reason: 'Right ankle sprain evaluation following sporting activity.',
    symptoms: 'Swelling on lateral malleolus, difficulty weight-bearing.',
    status: 'Upcoming',
    roomNumber: 'Orthopedic Suite 1A',
    createdAt: '2026-08-18',
  },
  {
    id: 'apt-106',
    patientId: 'PID-2024-0522',
    patientName: 'Amina Bello',
    patientPhone: '+234 814 670 3321',
    doctorId: 'user-doc-5',
    doctorName: 'Dr. Helen Davies',
    department: 'Women\'s Health',
    specialization: 'Obstetrics & Gynecology',
    date: '2026-06-12',
    time: '10:00',
    reason: 'Routine pelvic ultrasound and consultation.',
    status: 'Completed',
    notes: 'Scan unremarkable. Reassured patient.',
    roomNumber: 'Gynae Clinic 4',
    createdAt: '2026-06-08',
  },
];

export const INITIAL_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec-001',
    recordNumber: 'EMR-2026-0418',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    visitDate: '2026-07-10',
    department: 'Internal Medicine',
    chiefComplaint: 'Sore throat, moderate fever, and non-productive cough for 4 days.',
    symptoms: ['Sore throat', 'Fever', 'Dry cough', 'Body aches', 'Mild nasal congestion'],
    diagnosis: 'Acute Upper Respiratory Tract Infection (ICD-10: J06.9) / Mild Pharyngitis',
    icdCode: 'J06.9',
    treatmentPlan: 'Hydration therapy, oral Paracetamol 1000mg TID, Azithromycin 500mg daily for 3 days, saline gargles.',
    clinicalNotes: 'Pharyngeal mucosa mildly erythematous, no exudates on tonsils. Lungs clear to auscultation bilaterally. Patient advised on adequate rest and to return if shortness of breath develops.',
    vitals: {
      bloodPressure: '128/82 mmHg',
      heartRate: '78 bpm',
      temperature: '38.1 °C',
      respiratoryRate: '16 bpm',
      spO2: '98%',
      weight: '74.5 kg',
      height: '178 cm',
    },
    followUpDate: '2026-08-25',
  },
  {
    id: 'rec-002',
    recordNumber: 'EMR-2026-0302',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    doctorId: 'user-doc-2',
    doctorName: 'Dr. Daniel Adeyemi',
    visitDate: '2026-05-18',
    department: 'Cardiology',
    chiefComplaint: 'Evaluation of elevated blood pressure readings recorded during employee fitness screening.',
    symptoms: ['Occasional occipital morning headaches', 'Stress-related palpitations'],
    diagnosis: 'Stage 1 Essential Hypertension (ICD-10: I10) & Borderline Dyslipidemia',
    icdCode: 'I10',
    treatmentPlan: 'Initiated lifestyle modification: low sodium diet (<2g/day), aerobic exercise 150 min/wk. Prescribed Amlodipine 5mg daily. Ordered fasting lipid profile and 12-lead ECG.',
    clinicalNotes: 'S1, S2 present, no murmurs heard. Peripheral pulses intact. No pedal edema noted. Patient counseled on adherence to home BP monitoring diary.',
    vitals: {
      bloodPressure: '142/92 mmHg',
      heartRate: '82 bpm',
      temperature: '36.7 °C',
      respiratoryRate: '14 bpm',
      spO2: '99%',
      weight: '75.2 kg',
      height: '178 cm',
    },
    followUpDate: '2026-09-02',
  },
  {
    id: 'rec-003',
    recordNumber: 'EMR-2026-0115',
    patientId: 'PID-2024-0522',
    patientName: 'Amina Bello',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    visitDate: '2026-01-15',
    department: 'Internal Medicine',
    chiefComplaint: 'Post-prandial epigastric burning sensation aggravated by spicy foods.',
    symptoms: ['Heartburn', 'Epigastric discomfort', 'Acid regurgitation', 'Bloating'],
    diagnosis: 'Gastroesophageal Reflux Disease (GERD) with Mild Gastritis (ICD-10: K21.9)',
    icdCode: 'K21.9',
    treatmentPlan: 'Omeprazole 20mg once daily 30 minutes before breakfast for 4 weeks. Antacid suspension as needed. Dietary counseling.',
    clinicalNotes: 'Abdomen soft, mild non-rebound tenderness in the epigastrium. Bowel sounds normal. Helicobacter pylori stool antigen test ordered.',
    vitals: {
      bloodPressure: '116/74 mmHg',
      heartRate: '72 bpm',
      temperature: '36.5 °C',
      respiratoryRate: '15 bpm',
      spO2: '99%',
      weight: '58.0 kg',
      height: '165 cm',
    },
    followUpDate: '2026-02-20',
  },
  {
    id: 'rec-004',
    recordNumber: 'EMR-2026-0604',
    patientId: 'PID-2024-0604',
    patientName: 'Chinedu Eze',
    doctorId: 'user-doc-4',
    doctorName: 'Dr. Kingsley Nwosu',
    visitDate: '2026-06-04',
    department: 'Surgery & Orthopedics',
    chiefComplaint: 'Twisted right ankle while playing football on campus field.',
    symptoms: ['Localized lateral ankle pain', 'Moderate swelling', 'Antalgic gait'],
    diagnosis: 'Grade II Inversion Sprain of Right Ankle (ICD-10: S93.4)',
    icdCode: 'S93.4',
    treatmentPlan: 'R.I.C.E. protocol (Rest, Ice, Compression bandage, Elevation). Ibuprofen 400mg TID with food for 5 days. Ankle support brace.',
    clinicalNotes: 'X-ray Right Ankle AP & Lateral showed no cortical breach or fracture. Anterior talofibular ligament tenderness noted.',
    vitals: {
      bloodPressure: '124/80 mmHg',
      heartRate: '76 bpm',
      temperature: '36.6 °C',
      respiratoryRate: '16 bpm',
      spO2: '98%',
      weight: '82.0 kg',
      height: '182 cm',
    },
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-201',
    prescriptionNumber: 'RX-2026-0812',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    doctorId: 'user-doc-2',
    doctorName: 'Dr. Daniel Adeyemi',
    dateIssued: '2026-07-15',
    medication: 'Amlodipine Besylate',
    genericName: 'Amlodipine',
    dosage: '5 mg',
    frequency: 'Once daily in the morning (OD)',
    duration: '90 days',
    route: 'Oral',
    instructions: 'Take tablet with a glass of water every morning. Do not skip doses. Monitor blood pressure weekly.',
    status: 'Active',
    refillsRemaining: 2,
    diagnosisReference: 'Stage 1 Essential Hypertension (ICD-10: I10)',
  },
  {
    id: 'rx-202',
    prescriptionNumber: 'RX-2026-0708',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    dateIssued: '2026-07-10',
    medication: 'Azithromycin Monohydrate',
    genericName: 'Azithromycin',
    dosage: '500 mg',
    frequency: 'Once daily (OD)',
    duration: '3 days',
    route: 'Oral',
    instructions: 'Take 1 hour before or 2 hours after meals. Complete the entire 3-day course.',
    status: 'Completed',
    refillsRemaining: 0,
    diagnosisReference: 'Acute Upper Respiratory Tract Infection',
  },
  {
    id: 'rx-203',
    prescriptionNumber: 'RX-2026-0709',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    dateIssued: '2026-07-10',
    medication: 'Paracetamol Tablets BP',
    genericName: 'Acetaminophen',
    dosage: '1000 mg (2 x 500mg)',
    frequency: 'Three times daily after meals (TDS) as needed for fever/pain',
    duration: '5 days',
    route: 'Oral',
    instructions: 'Do not exceed 4,000 mg in 24 hours. Stop once symptoms subside.',
    status: 'Completed',
    refillsRemaining: 0,
    diagnosisReference: 'Symptomatic fever management',
  },
  {
    id: 'rx-204',
    prescriptionNumber: 'RX-2026-0118',
    patientId: 'PID-2024-0522',
    patientName: 'Amina Bello',
    doctorId: 'user-doc-1',
    doctorName: 'Dr. Sarah Mitchell',
    dateIssued: '2026-01-15',
    medication: 'Omeprazole Delayed-Release Capsules',
    genericName: 'Omeprazole',
    dosage: '20 mg',
    frequency: 'Once daily before breakfast (OD)',
    duration: '30 days',
    route: 'Oral',
    instructions: 'Swallow whole with water; do not crush or chew capsule.',
    status: 'Completed',
    refillsRemaining: 0,
    diagnosisReference: 'GERD / Gastritis',
  },
  {
    id: 'rx-205',
    prescriptionNumber: 'RX-2026-0605',
    patientId: 'PID-2024-0604',
    patientName: 'Chinedu Eze',
    doctorId: 'user-doc-4',
    doctorName: 'Dr. Kingsley Nwosu',
    dateIssued: '2026-06-04',
    medication: 'Ibuprofen Tablets',
    genericName: 'Ibuprofen',
    dosage: '400 mg',
    frequency: 'Three times daily after meals (TDS)',
    duration: '5 days',
    route: 'Oral',
    instructions: 'Always take with food or milk to prevent stomach irritation.',
    status: 'Completed',
    refillsRemaining: 0,
    diagnosisReference: 'Ankle Sprain analgesia',
  },
];

export const INITIAL_LAB_RESULTS: LabResult[] = [
  {
    id: 'lab-301',
    labNumber: 'LAB-2026-0814',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    requestedByDoctor: 'Dr. Daniel Adeyemi (Cardiology)',
    testName: 'Fast Lipid Profile & Cardiovascular Risk Panel',
    category: 'Biochemistry',
    sampleDate: '2026-08-14',
    completionDate: '2026-08-15',
    status: 'Completed',
    overallSummary: 'Borderline elevated total cholesterol and LDL fractions; Triglycerides and HDL within acceptable clinical bounds.',
    parameters: [
      { name: 'Total Cholesterol', value: '215', unit: 'mg/dL', referenceRange: '< 200', flag: 'Elevated' },
      { name: 'HDL Cholesterol', value: '48', unit: 'mg/dL', referenceRange: '> 40', flag: 'Normal' },
      { name: 'LDL Cholesterol', value: '138', unit: 'mg/dL', referenceRange: '< 100', flag: 'Elevated' },
      { name: 'Triglycerides', value: '145', unit: 'mg/dL', referenceRange: '< 150', flag: 'Normal' },
      { name: 'Cholesterol / HDL Ratio', value: '4.48', unit: 'ratio', referenceRange: '< 5.0', flag: 'Normal' },
    ],
    pathologistNotes: 'Specimen was collected after 12-hour overnight fast without lipemia or hemolysis.',
    doctorComments: 'Discuss dietary fat reduction and consider low-dose Statin therapy during next review.',
  },
  {
    id: 'lab-302',
    labNumber: 'LAB-2026-0815',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    requestedByDoctor: 'Dr. Sarah Mitchell (Internal Medicine)',
    testName: 'Comprehensive Metabolic Panel (CMP) & Fasting Blood Sugar',
    category: 'Biochemistry',
    sampleDate: '2026-08-14',
    completionDate: '2026-08-15',
    status: 'Verified',
    overallSummary: 'Renal parameters, electrolytes, and liver transaminases within normal physiological reference ranges.',
    parameters: [
      { name: 'Fasting Blood Glucose', value: '92', unit: 'mg/dL', referenceRange: '70 - 99', flag: 'Normal' },
      { name: 'Serum Creatinine', value: '0.94', unit: 'mg/dL', referenceRange: '0.70 - 1.30', flag: 'Normal' },
      { name: 'Blood Urea Nitrogen (BUN)', value: '14.2', unit: 'mg/dL', referenceRange: '7.0 - 20.0', flag: 'Normal' },
      { name: 'Estimated GFR (eGFR)', value: '> 90', unit: 'mL/min/1.73m²', referenceRange: '> 60', flag: 'Normal' },
      { name: 'Sodium (Na+)', value: '140', unit: 'mmol/L', referenceRange: '135 - 145', flag: 'Normal' },
      { name: 'Potassium (K+)', value: '4.2', unit: 'mmol/L', referenceRange: '3.5 - 5.0', flag: 'Normal' },
    ],
    pathologistNotes: 'Specimen verified by Dr. A. B. Cole (Consultant Chemical Pathologist).',
    doctorComments: 'Kidney and baseline metabolic function are in excellent condition.',
  },
  {
    id: 'lab-303',
    labNumber: 'LAB-2026-0710',
    patientId: 'PID-2024-0418',
    patientName: 'Emmanuel O. Kalu',
    requestedByDoctor: 'Dr. Sarah Mitchell (Internal Medicine)',
    testName: 'Full Blood Count (FBC) with Differential',
    category: 'Hematology',
    sampleDate: '2026-07-10',
    completionDate: '2026-07-10',
    status: 'Completed',
    overallSummary: 'Mild neutrophilic leukocytosis consistent with active upper respiratory infection.',
    parameters: [
      { name: 'White Blood Cell (WBC)', value: '11.4', unit: 'x10^9/L', referenceRange: '4.0 - 10.0', flag: 'Elevated' },
      { name: 'Neutrophils %', value: '74', unit: '%', referenceRange: '40 - 70', flag: 'Elevated' },
      { name: 'Lymphocytes %', value: '20', unit: '%', referenceRange: '20 - 45', flag: 'Normal' },
      { name: 'Hemoglobin (Hb)', value: '14.8', unit: 'g/dL', referenceRange: '13.5 - 17.5', flag: 'Normal' },
      { name: 'Hematocrit (PCV)', value: '44.2', unit: '%', referenceRange: '40.0 - 52.0', flag: 'Normal' },
      { name: 'Platelet Count', value: '280', unit: 'x10^9/L', referenceRange: '150 - 450', flag: 'Normal' },
    ],
    pathologistNotes: 'No immature white cells or red blood cell abnormalities observed on peripheral film.',
    doctorComments: 'Expected inflammatory response to URTI. Treated with Azithromycin.',
  },
  {
    id: 'lab-304',
    labNumber: 'LAB-2026-0116',
    patientId: 'PID-2024-0522',
    patientName: 'Amina Bello',
    requestedByDoctor: 'Dr. Sarah Mitchell (Internal Medicine)',
    testName: 'Helicobacter Pylori Stool Antigen Assay',
    category: 'Microbiology',
    sampleDate: '2026-01-16',
    completionDate: '2026-01-17',
    status: 'Completed',
    overallSummary: 'Negative for H. pylori stool antigen.',
    parameters: [
      { name: 'H. Pylori Antigen', value: 'Negative', unit: 'qualitative', referenceRange: 'Negative', flag: 'Normal' },
    ],
    pathologistNotes: 'Immunoassay test performed using valid standard controls.',
    doctorComments: 'Confirmed acid reflux / gastritis without bacterial colonization.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-pat-1',
    title: 'Upcoming Appointment Reminder',
    message: 'You have a scheduled clinical consultation with Dr. Sarah Mitchell on Aug 25, 2026 at 10:30 AM in Room 3B.',
    timestamp: '2026-08-19 08:30',
    read: false,
    category: 'Appointment',
    actionLink: 'appointments',
  },
  {
    id: 'notif-2',
    userId: 'user-pat-1',
    title: 'Laboratory Result Available',
    message: 'Your Fast Lipid Profile & Cardiovascular Risk Panel results are now ready and available for review.',
    timestamp: '2026-08-15 14:10',
    read: false,
    category: 'Laboratory',
    actionLink: 'lab-results',
  },
  {
    id: 'notif-3',
    userId: 'user-pat-1',
    title: 'Prescription Refill Notice',
    message: 'Your prescription for Amlodipine Besylate (5mg) has 2 remaining refills on your file.',
    timestamp: '2026-08-10 09:00',
    read: true,
    category: 'Prescription',
    actionLink: 'prescriptions',
  },
  {
    id: 'notif-4',
    userId: 'user-pat-1',
    title: 'System Notice: Maintenance Window',
    message: 'Academic server maintenance is scheduled for Sunday 12:00 AM - 02:00 AM. Portal services will remain unaffected.',
    timestamp: '2026-08-05 11:00',
    read: true,
    category: 'System',
    actionLink: 'notifications',
  },
  {
    id: 'notif-5',
    userId: 'user-doc-1',
    title: 'New Appointment Booked',
    message: 'Patient Amina Bello has booked an appointment for General Clearance on Aug 20, 2026 at 09:45 AM.',
    timestamp: '2026-08-16 10:15',
    read: false,
    category: 'Appointment',
    actionLink: 'appointments',
  },
  {
    id: 'notif-6',
    userId: 'user-admin-1',
    title: 'New Doctor Account Verification Required',
    message: 'A new doctor profile (Dr. Kingsley Nwosu) has completed credentials registration.',
    timestamp: '2026-08-18 16:30',
    read: false,
    category: 'System',
    actionLink: 'admin-dashboard',
  },
];

export const INITIAL_SYSTEM_LOGS: SystemLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-08-19 10:22:45',
    user: 'Dr. Sarah Mitchell',
    role: 'Doctor',
    action: 'Prescription Created',
    details: 'Issued RX-2026-0812 (Amlodipine 5mg) to Patient PID-2024-0418',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-19 09:14:10',
    user: 'Emmanuel O. Kalu',
    role: 'Patient',
    action: 'Appointment Booked',
    details: 'Scheduled visit for 2026-08-25 with Dr. Sarah Mitchell',
    ipAddress: '10.0.4.112',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-18 16:30:00',
    user: 'Prof. J. C. Okafor',
    role: 'Admin',
    action: 'Doctor Profile Approved',
    details: 'Verified credentials for MD-ORTH-11843 (Dr. Kingsley Nwosu)',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'log-4',
    timestamp: '2026-08-15 14:10:22',
    user: 'Dr. A. B. Cole',
    role: 'Staff/Lab',
    action: 'Lab Results Uploaded',
    details: 'Uploaded chemistry results LAB-2026-0814 for Patient PID-2024-0418',
    ipAddress: '192.168.2.88',
  },
  {
    id: 'log-5',
    timestamp: '2026-08-14 11:05:18',
    user: 'Amina Bello',
    role: 'Patient',
    action: 'Patient Profile Updated',
    details: 'Emergency contact information updated',
    ipAddress: '10.0.4.119',
  },
];
